Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Simulation = fdsreader.Simulation('./non-predefined_fuel/')

time = Simulation.slices[0].get_nearest_timestep(3)

plt.imshow(Simulation.slices[0][0].data[time].T, 
               origin = 'lower', 
               extent = Simulation.slices[0].extent.as_list())
        
plt.title('Pentane')
plt.xlabel("x / m")
plt.ylabel("z / m")
plt.colorbar(label = "Mass Fraction")
        
plt.savefig("figs/mass_frac_pentane.svg")
plt.close()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m Simulation [38;5;241m=[39m [43mfdsreader[49m[38;5;241;43m.[39;49m[43mSimulation[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m./non-predefined_fuel/[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      3[0m time [38;5;241m=[39m Simulation[38;5;241m.[39mslices[[38;5;241m0[39m][38;5;241m.[39mget_nearest_timestep([38;5;241m3[39m)
[1;32m      5[0m plt[38;5;241m.[39mimshow(Simulation[38;5;241m.[39mslices[[38;5;241m0[39m][[38;5;241m0[39m][38;5;241m.[39mdata[time][38;5;241m.[39mT, 
[1;32m      6[0m                origin [38;5;241m=[39m [38;5;124m'[39m[38;5;124mlower[39m[38;5;124m'[39m, 
[1;32m      7[0m                extent [38;5;241m=[39m Simulation[38;5;241m.[39mslices[[38;5;241m0[39m][38;5;241m.[39mextent[38;5;241m.[39mas_list())

File [0;32m/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/fdsreader/simulation.py:60[0m, in [0;36mSimulation.__new__[0;34m(cls, path)[0m
[1;32m     59[0m [38;5;28;01mdef[39;00m [38;5;21m__new__[39m([38;5;28mcls[39m, path: [38;5;28mstr[39m):
[0;32m---> 60[0m     smv_file_path [38;5;241m=[39m [43mget_smv_file[49m[43m([49m[43mpath[49m[43m)[49m
[1;32m     61[0m     root_path [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mdirname(smv_file_path)
[1;32m     63[0m     [38;5;28;01mwith[39;00m [38;5;28mopen[39m(smv_file_path, [38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m) [38;5;28;01mas[39;00m infile:

File [0;32m/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/fdsreader/utils/data.py:97[0m, in [0;36mget_smv_file[0;34m(path)[0m
[1;32m     95[0m     [38;5;28;01mreturn[39;00m path [38;5;241m+[39m [38;5;124m"[39m[38;5;124m.smv[39m[38;5;124m"[39m
[1;32m     96[0m [38;5;28;01melse[39;00m:
[0;32m---> 97[0m     [38;5;28;01mraise[39;00m [38;5;167;01mIOError[39;00m([38;5;124m"[39m[38;5;124mThe given path does neither point to a directory nor a file: [39m[38;5;124m"[39m [38;5;241m+[39m path)

[0;31mOSError[0m: The given path does neither point to a directory nor a file: ./non-predefined_fuel/

